name: novel_log_local
description: A Flutter application for keeping your novel log locally.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.0.1
  hive_generator: 1.1.0
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/